### PR TITLE
update pagerank

### PR DESCRIPTION
**Pull request by miajeffris**
Utilized networkx pagerank function, excluded self loops before pagerank calculation

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
I keep getting a convergence error from the page rank function. Were you seeing this on your other branch? I wonder what's different here.

**Comment by miajeffris** [comment]
> I keep getting a convergence error from the page rank function. Were you seeing this on your other branch? I wonder what's different here.

I wasn't getting any errors when I used this code on my other branch for the GRNdb matrix, so I'm not sure what it could be. Maybe it has to do with some of the iterating that goes on after add_edges and set_edges have been called in the creation of the network. If there is some other part of the code that is expecting i x j (83x83) edges, would that cause a convergence error since self-edges are excluded in this update? I can sift through the rest of graph.py to see if there could be something like this causing an error. It's weird that the error is originating with the pagerank function though, since it should be compatible with other networkx functions and graph attributes.

**Comment by miajeffris** [comment]
> > I keep getting a convergence error from the page rank function. Were you seeing this on your other branch? I wonder what's different here.
> 
> I wasn't getting any errors when I used this code on my other branch for the GRNdb matrix, so I'm not sure what it could be. Maybe it has to do with some of the iterating that goes on after add_edges and set_edges have been called in the creation of the network. If there is some other part of the code that is expecting i x j (83x83) edges, would that cause a convergence error since self-edges are excluded in this update? I can sift through the rest of graph.py to see if there could be something like this causing an error. It's weird that the error is originating with the pagerank function though, since it should be compatible with other networkx functions and graph attributes.

I can see that the old pagerank gets called in the bar graph functions, I forgot to update those functions with my last commit. Do you think that editing those will solve the convergence error?

**Comment by aarmey** [comment]
@miajeffris hmm... indeed, it would be good to update the bar graph functions so they point to the right place too. To figure out the convergence issue, could you open a PR of the branch where this is working, and tag me? I'll try and see if I can spot the critical difference.

**Comment by miajeffris** [comment]
> @miajeffris hmm... indeed, it would be good to update the bar graph functions so they point to the right place too. To figure out the convergence issue, could you open a PR of the branch where this is working, and tag me? I'll try and see if I can spot the critical difference.

Just tagged you in the PR where this is working for the GRNdb network

**Comment by aarmey** [comment]
@miajeffris I don't see a call to `nx.pagerank` on that other branch?

**Comment by aarmey** [comment]
See Slack message.

**Pull request closed without merging**
