### PR TITLE
networkx.pagerank() in GRNdb network

### PR DESCRIPTION
**Pull request by miajeffris**
in the set_nodes function of grndb_network.py, I am able to use networkx's pagerank function without error, even though there are many leaf nodes that result from plotting the GRNdb graph

### CODE REVIEW

**Comment by aarmey** [comment]
Huh... I agree that it looks like this runs it successfully.

Since we have to overlay this graph on the `w` matrix, it'd probably be best to run PageRank in matrix form here, too, since NetworkX can easily convert from graph to adjacency matrix.

**Comment by Farnazmdi** [comment]
@miajeffris could you please take a look at the build? it keeps failing when I try to re-run.

**Comment by miajeffris** [comment]
> @miajeffris could you please take a look at the build? it keeps failing when I try to re-run.

Oh, the "manuscript build" button? I'm wondering if the issue is that I created a new figure (figure 5) and maybe I need to manipulate the manuscript code somehow to get it to show up?

**Comment by Farnazmdi** [comment]
I did not mean the manuscript build. If you click on `details` on the build entry, you will see this:
image

**Comment by aarmey** [comment]
What would make you believe this would build differently depending upon the branch?

I'm not sure you can use an `or` statement like that in the exception handling. I'd look into that.

**Comment by Farnazmdi** [comment]
After increasing the threshold in `add_edges()` node 12 was removed from the graph `G`. Because node 12 was referring to a gene that was one of the full-resistants, and appeared in the list of the indexes, but was not found in G, we had this error. I removed node 12 from the list and it seems node 12 was the only gene with this problem. 

I suggest we merge this and then I will play with the PageRank and Mia can work on some documentation.

**Comment by miajeffris** [comment]
> After increasing the threshold in `add_edges()` node 12 was removed from the graph `G`. Because node 12 was referring to a gene that was one of the full-resistants, and appeared in the list of the indexes, but was not found in G, we had this error. I removed node 12 from the list and it seems node 12 was the only gene with this problem.
> 
> I suggest we merge this and then I will play with the PageRank and Mia can work on some documentation.

Sounds good to me!

**Review by aarmey — APPROVED** [review]
Good catch.

**Pull request merged**
