### PR TITLE
regularization

### PR DESCRIPTION
**Pull request by Farnazmdi**
adding regularization to the least square fitting of w.

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Here is with lambda 10:
image

@aarmey Should I discard it or keep the regularization? In this, the significance of MAFA is alleviated and SOX10, EGFR, and JUN are more significant.

**Comment by Farnazmdi** [comment]
Actually, let me work a bit more on it to find a good lambda.

**Comment by aarmey** [comment]
To work this would need to be reflected in the non-linear fitting, too. I still think it's more important to look at a small model set of genes first.

**Comment by Farnazmdi** [comment]
Yes, sorry, will do that first.

**Pull request closed without merging**
