### PR TITLE
Tensor & cleanning

### PR DESCRIPTION
**Pull request by Farnazmdi**
I simplified `mergedFittin()` a bit. `commonGenes()` now works with any number of cell lines given. And created a tensor form of the intersection of all cell lines in the LINCS dataset.
I intend to do some data exploration (like what we discussed for the drug response model). To keep the PR simple I will add the tensorly analysis in another PR.
Please let me know if you think I should not pursue this. Thanks.

### CODE REVIEW

**Comment by aarmey** [comment]
Interesting. What percentage of the data has to be thrown out to put it into tensor form?

**Comment by Farnazmdi** [comment]
The number of overlapping genes is 593, so I am guessing a little less than 50%.

**Comment by aarmey** [comment]
It might be better to organize it including all the data, but having missing values. It’s easy, then, to remove missing values later.

**Comment by Farnazmdi** [comment]
Got it, thanks, will do.

**Comment by Farnazmdi** [comment]
@aarmey Could you please review this PR? The tensor of the intersection of genes among 6 cell lines is ready. The tensor has the dimension of 593 x 594 x 6. I also z-scored each condition. 
Will do the decomposition in another PR.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
